version: '3.8'
services:
  web:
    image: pindinga1/openvas:latest
    container_name: openvas
    ports:
      - "9392:9392"
    environment:
      - OPENVAS_PASSWORD=admin
    volumes:
      - plugins:/var/lib/openvas
      - feeds:/var/lib/gvm
      - postgresql:/var/lib/postgresql/15/main
volumes:
  feeds:
  plugins:
  postgresql: