version: '3.8'
services:
  web:
    image: pindinga1/openvas:latest
    container_name: openvas
    ports:
      - "9392:9392"
    environment:
      - OPENVAS_PASSWORD=Admin123!
    volumes:
      - plugins:/var/lib/openvas
      - feeds:/var/lib/gvm
      - postgresql:/var/lib/postgresql/15/main
      - notus:/var/lib/notus
volumes:
  plugins:
  feeds:
  postgresql:
  notus: